config/routes.rb
RMTest::Application.routes.draw do
  
  match "users/send_message/:id" => 'users#send_message'
  
  match "users/send_message.:id" => 'users#send_message'
  
  match "users/message/:id/edit" => 'messages#edit'
   
  match 'users.:id' => 'users#show'
  
  match 'reviews/new.:id' => 'reviews#new'
  
  match "programs/create_review.:id" => 'programs#create_review'

  resources :messages

  resources :reviews

  devise_for :users
  
  resources :users do 
    post :send_message, :on => :collection
  end
  

  resources :programs do
  	resources :reviews
  	post :create_review, :on => :collection
  	end
  	

  resources :organizations do
    resources :comments

  end

  get "pages/home"

 root :to => 'pages#home'

end

app/models/program.rb
class Program < ActiveRecord::Base
belongs_to :organization
has_many :reviews
attr_accessible :id, :photo

# Paperclip
has_attached_file :photo,
  :styles => {
    :thumb=> "100x100#",
    :small  => "150x150>",
    :medium => "300x300>",
    :large =>   "400x400>" }
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render :json => @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
  
  def create_review
     @program = Program.find(params[:id])
     @review = Review.create
     @review.program_id = @program.id
     @review.user_id = current_user.id
     redirect_to edit_review_path(@review.id)
   end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :weekly_cost %><br />
    <%= f.number_field :weekly_cost %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :organization_id %><br />
    <%= f.number_field :organization_id %>
  </div>

  <div><%= f.label 'Add a photo' %>
  <%= f.file_field :photo %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Weekly cost</th>
    <th>Location</th>
    <th>Organization</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programs.each do |program| %>
  <tr>
    <td><%= program.name %></td>
    <td><%= program.description %></td>
    <td><%= program.weekly_cost %></td>
    <td><%= program.location %></td>
    <td><%= Org_Namer(program.organization_id)  %></td>
    <td><%= link_to 'Show', program %></td>
    <td><%= link_to 'Edit', edit_program_path(program) %></td>
    <td><%= link_to 'Destroy', program, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<% if @program.photo.exists? then %>
<p><%= image_tag @event.photo.url(:medium) %></p>
<% else %>
<p> There are no photos attached, upload one. </p>
<% end %>

<p>
  <b>Name:</b>
  <%= @program.name %>
</p>

<p>
  <b>Photo:</b>
  <%= image_tag @program.photo.url %>
</p>

<p>
  <b>Description:</b>
  <%= @program.description %>
</p>

<p>
  <b>Weekly cost:</b>
  <%= @program.weekly_cost %>
</p>

<p>
  <b>Location:</b>
  <%= @program.location %>
</p>

<p>
  <b>Organization:</b>
    <td><%= Org_Namer(@program.organization_id) %></td>
</p>


<h2>Submit a Review:</h2>
<p><%= link_to "Submit a Review", create_review_programs_path(@program)%></p>
<%= link_to "Add to favorites", %>

<h2>Reviews:</h2>
<% if (@program.reviews).empty? %>
This program does not yet have any reviews.
<% else %>
	<% (@program.reviews).each do |f|%>
	<%= link_to "Review # #{f.id}", f %>
	<br />
	<% end %>
<% end %>