config/routes.rb
RMTest::Application.routes.draw do
  
  match "users/send_message/:id" => 'users#send_message'
  
  match "users/send_message.:id" => 'users#send_message'
  
  match "users/message/:id/edit" => 'messages#edit'
   
  match 'users.:id' => 'users#show'
  
  match 'reviews/new.:id' => 'reviews#new'
  
  match "programs/create_review.:id" => 'programs#create_review'

  resources :messages

  resources :reviews

  devise_for :users
  
  resources :users do 
    post :send_message, :on => :collection
  end
  

  resources :programs do
  	resources :reviews
  	post :create_review, :on => :collection
  	end
  	

  resources :organizations do
    resources :comments

  end

  get "pages/home"

 root :to => 'pages#home'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
has_many :comments
has_many :programs

def self.search(search)
	if search
		find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
	else
		find(:all)
	end
end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    # @organizations = Organization.all
  	@organizations = Organization.search(params[:search])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end


  end

  # GET /organizations/1
  # GET /organizations/1.json
  
   
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
    <%= f.label :program_id%><br />
    <%= f.number_field :program_id %>
  </div>
  <div class="actions">
    <%= f.submit %>     
</div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>



<%= form_tag organizations_path, :method => 'get' do %>  
  <p>  
    <%= text_field_tag :search, params[:search] %>  
    <%= submit_tag "Search", :name => nil %>  
  </p>  
<% end %> 

<table>
  <tr>
	<th>ID</th>
     <th>Name</th>
    <th>Description</th>
	<th>Programs</th>
     <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
   <td><%= organization.id %></td>
  	<td><%= organization.name %></td>
    <td><%= organization.description %></td>
    <td><%= organization.programs %></td>
        <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>

<p>
  <b>Description:</b>
  <%= @organization.description %>
</p>

<p>
  <b>Programs:</b>
  <%= @organization.program_id %>
</p>



<h2>Comments</h2>
<% @organization.comments.each do |comment| %>
    <p>
      <b>Commenter:</b>
      <%= comment.commenter %>
    </p>

    <p>
      <b>Comment:</b>
      <%= comment.body %>
    </p>
<% end %>



<h2>Add a comment:</h2>
<%= form_for([@organization, @organization.comments.build]) do |f| %>
    <div class="field">
      <%= f.label :commenter %><br />
      <%= f.text_field :commenter %>
    </div>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>