config/routes.rb
RMTest::Application.routes.draw do
  
  match "users/send_message/:id" => 'users#send_message'
  
  match "users/send_message.:id" => 'users#send_message'
  
  match "users/message/:id/edit" => 'messages#edit'
   
  match 'users.:id' => 'users#show'
  
  match 'reviews/new.:id' => 'reviews#new'
  
  match "programs/create_review.:id" => 'programs#create_review'

  resources :messages

  resources :reviews

  devise_for :users
  
  resources :users do 
    post :send_message, :on => :collection
  end
  

  resources :programs do
  	resources :reviews
  	post :create_review, :on => :collection
  	end
  	

  resources :organizations do
    resources :comments

  end

  get "pages/home"

 root :to => 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RMTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<a href="/">Home</a> |
<%= link_to "Organizations", {:controller => 'organizations', :action => 'index'}  %> |
<%= link_to "Programs", {:controller => 'programs', :action => 'index'}  %> |
<%= link_to "View all users", users_path %> |
<% if !user_signed_in? %>
<%= link_to "Sign up!", new_user_registration_path %> |
<%= link_to "Sign in", new_user_session_path %> |
<% else %>
<%= link_to 'Sign out', destroy_user_session_path, :method => :delete%> |
<%= link_to "Messages", messages_path %> <%= current_user.unread_message_count%> |
<%= link_to "Your Profile Page", users_path(current_user.id)%>
<% end %>



<%= yield %>

</body>
</html>